include:
  - project: 'bhpc/ci'
    file: '/java11.yml'
  - project: 'bhpc/ci'
    file: '/helm/base.yml'
  - project: 'bhpc/ci'
    file: '/helm/master.yml'

variables:
  APP_ENTRY: "saas-admin-server"
  SERVICE_NAME: "saas-admin-server"
  APP_HTTP_PORT: 7501
  APP_GRPC_PORT: 7401