saas:
  admin:
    url: "https://saas.nucleex.com/"
grpc-client:
  stub-deadline: 8000
  channel-info:
    - channel-name: 'adminCommonGrpcChannel'
      host: 'localhost'
      port: 7401
      use-ssl: false
    - channel-name: 'bhChannel'
      host: 'bh-server.bluehelix'
      port: 7011
      use-ssl: false
    - channel-name: 'saasAdminGrpcChannel'
      host: 'localhost'
      port: 7401
      use-ssl: false
    - channelName: 'exAdminGrpcChannel'
      host: 'ex-admin-grpc.exchange'
      port: 7402
      useSsl: false
    - channel-name: 'commonServerChannel'
      host: 'common-server.broker'
      port: 7220
      use-ssl: false
    - channel-name: 'quoteChannel'
      host: 'quote-data-service.exchange'
      port: 7063
      use-ssl: false
    - channel-name: 'quoteDataChannel'
      host: 'quote-data-service.exchange'
      port: 7063
      use-ssl: false
    - channel-name: 'marginServerChannel'
      host: 'margin-server.bluehelix'
      port: 7232
      use-ssl: false

awsstorage:
  aws:
    bucket: private.nucleex.com
    access-key: XXX
    secret-key: XXX
    region-name: ap-southeast-1
  access-os-file-key: XXX
  public:
    static-url: https://static.nucleex.com/
    prefix: token/
    aws:
      bucket: static.nucleex.com
      access-key: XXX
      secret-key: XXX
      region-name: ap-southeast-1
authorize:
  referer:
    check: false
    domain: "http://card.nucleex.com/"
  newversion: true
  ignore:
    resource: "/api/v1/broker/query_simple_brokers,/api/v1/exchange/query_simple_exchanges,/api/v1/user,/api/v1/instance,/internal/health,/api/v1/country/list,/api/v1/platform_account,/api/v1/role_auth/user/auth_path/list,/api/v1/helper/"
    garesource: "/api/v1/security"
  gaenable: false
  token:
    jwt:
      secret: XXX
      expire_in_seconds: 14400
  cookie:
    domain: "nucleex.com"
    secure: false